[Back to assignment 7](_Oving7.ipynb)
# Gaussian Elimination

## a)

Assign the variable `matrix` for the augmented matrix of the set of equations

$$
x - 2y + 1z = 0$$
$$\quad\quad 2y - 8z = 8$$
$$ -4x + 5y + 9z = -9$$

***Write code in the block below***

In [7]:
import numpy as np
matrix = np.array([[1, -2, 1, 0],[0, 2, -8, 8],[-4, 5, 9, -9]])
print(matrix)


[[ 1 -2  1  0]
 [ 0  2 -8  8]
 [-4  5  9 -9]]


## b) 
Make a function `add` that takes a matrix `A` and adds a multiple of one row to another. The function should accept `A`, two integers `i1` and `i2` as input (the integers specify which rows to add) and a number `num`. The function should take the rows `A[i1,:]` and `A[i2,:]` then add `num*A[i1,:]` to `A[i2,:]`. The function shall not return anything, but only make changes to `A[i2,:]`.

In [8]:
import numpy as np

def add(A, i1, i2, num):
    A[i2,:] += num * A[i1,:]
    print('Changes made')
    return 
A = np.array([[2.,3.,4.], [5.,-3.,6.]])
add(A,0, 1, -5/2) # add (-5/2) times row 0 to row 1
print(A)


Changes made
[[  2.    3.    4. ]
 [  0.  -10.5  -4. ]]


## c)

Make a function `swap` that takes a matrix `A` and two integers `i1` and `i2`, and then swaps the `i1` and `i2` rows of `A`. The function shall not return anything, just swaps the rows in `A`.


In [9]:
def swap(A, i1, i2):
    temp = np.array(A[i1,:])
    A[i1,:] = A[i2,:]
    A[i2,:] = temp

A = np.array([[2.,3.,4.], [5.,-3.,6.]])
swap(A,0, 1)
print(A)



[[ 5. -3.  6.]
 [ 2.  3.  4.]]


## d)
Write a function `getMaxRow` that takes an augmented matrix `A` (with `n` rows and `n+1` columns) and two integers `i` and `j` that specify the row and column of the pivot element. The function should return the index of the row with the largest element below the pivot row. The function should search down through the $j$'th column starting from the $i$'th row and return the *row index* of the element with maximal absolute value. This corresponds to step 1 above.

If `A` is an n x (n+1) matrix, you can use the built-in function `n = len(A)` to find n. (this returns the row dimension of `A`, regardless of the column dimension)

The array `A[i:n,j]` returns the elements in the column below and including the pivot element.

***write code in block below***


In [12]:
#For this subtask I got some starthelp from ChatGPT because the other tasks were much easier / shorter
#And I thought I was missing some function that would make this super easy. 

def getMaxRow(A, i, j):
    n = len(A)
    max_index = i
    max_value = abs(A[i,j])
    for k in range(i + 1, n):
        if abs(A[k,j]) > max_value:
            max_value = abs(A[k,j])
            max_index = k
    return max_index


A = np.array([[0.,1.,2.,3.], [4.,5.,6.,7.], [8.,9.,1.,2.]])
print(getMaxRow(A,0,0)) 

2


## e)

Write a function `rowOps` that takes as arguments a matrix `A` and two index numbers `i` and `j` that specify the pivot element. The function should first check whether `A[i,j]==0`, and return without doing anything if true. Otherwise, the function should add appropriate multiples of `A[i,:]` to each row with index larger than `i` in `A`, such that its entry with index `j` (i.e., in the pivot row) is set to zero.  This corresponds to step 3 above.

In [18]:
def rowOps(A, i, j):
    if A[i, j] == 0: #The code is useless if the pivot element is zerp, such as in example1.
        return print("Picot element is already 0")
    n = len(A)
    pivot_row = A[i, :]
    for i_2 in range(i + 1, n):
        factor = -A[i_2, j] / A[i, j]
        A[i_2, :] += factor * pivot_row
        A[i_2, j] = 0

A = np.array([[0.,1.,1.,3.], [1.,2,3,0], [1.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)
A = np.array([[8.,1.,1.,3.], [2.,6.,3.,0.], [4.,3.,4.,-2.]])
rowOps(A,0,0)
print(A)


Picot element is already 0
[[ 0.  1.  1.  3.]
 [ 1.  2.  3.  0.]
 [ 1.  3.  4. -2.]]
[[ 8.    1.    1.    3.  ]
 [ 0.    5.75  2.75 -0.75]
 [ 0.    2.5   3.5  -3.5 ]]


## f)
Now make a function `Gauss` that takes a matrix `A` as and uses `getMaxRow`, `rowOps` and `swap` functions to perform a Gaussian elimination with partial pivoting on `A`.


In [24]:
def Gauss(A):
    for i in range(len(A)):
        j = i
        swap(A, i, getMaxRow(A, i, j))
        rowOps(A, i, j)

A = np.array([[0., 1., 2., 3.], [4., 5., 6., 7.], [8., 9., 1., 2.]])
Gauss(A)
print(A)


[[8.  9.  1.  2. ]
 [0.  1.  2.  3. ]
 [0.  0.  4.5 4.5]]
